# Generated by Django 5.2.7 on 2025-10-23 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='Mensaje del usuario')),
                ('bot_response', models.TextField(verbose_name='Respuesta del bot')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('model_used', models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='Modelo utilizado')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['-created_at'],
            },
        ),
    ]
